# Generated by Django 3.1.7 on 2021-04-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
    ]
